Add bazel_local_coverage
Simba-Avionic/srp pull request #121
Opened 2024-07-19 09:09 UTC by Mateusz-Krajewski

2024-07-19 09:14 UTC, bartoszsnieg requested changes
Fajnie jak by pokazywał czy każda opcja z ifów jest sprawdzona

2024-07-19 09:55 UTC, Mateusz-Krajewski commented
> Fajnie jak by pokazywał czy każda opcja z ifów jest sprawdzona

![image](https://github.com/user-attachments/assets/869859a9-5f34-4ad7-a9d2-9e6952cac5eb)

2024-07-19 10:01 UTC, Mateusz-Krajewski commented
> Fajnie jak by pokazywał czy każda opcja z ifów jest sprawdzona

ten get_coverange_sh bardziej pod jakiś github action zrobiłem, a do użytku loklanie jest get_html, masz ładnie pokazane.
[WikiJS](https://simbav.toadres.pl/pl/Poradniki/Coverage)

2024-08-06 07:15 UTC, bartoszsnieg approved these changes

2024-08-06 07:15 UTC, merged