simulation core + gpio + i2c
Simba-Avionic/srp pull request #139
Opened 2024-11-07 11:45 UTC by Mateusz-Krajewski

2024-11-07 14:38 UTC, bartoszsnieg requested changes
Nazwy plików nie mają konwencji

2024-11-07 21:30 UTC, Mateusz-Krajewski commented
> Nazwy plików nie mają konwencji

poprawione

2024-11-08 13:40 UTC, bartoszsnieg approved these changes

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/temp_driver.cpp
> +    constexpr auto kManagerName = "w1_bus_master1";
```suggestion
    constexpr auto  kSensorPath = "/sys/bus/w1/devices/";
    constexpr auto kManagerName = "w1_bus_master1";
```

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/temp_driver.cpp
> +        uint8_t value = std::stoi(line);
```suggestion
       const uint8_t value = std::stoi(line);
```

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/temp_driver.cpp
> +    std::ifstream file(kSensorPath + sensorPhysicalID + "/resolution");
```suggestion
    const std::ifstream file(kSensorPath + sensorPhysicalID + "/resolution");
```

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/temp_driver.cpp
> +        double value = std::stoi(line) / 1000.0;
```suggestion
        const double value = static_cast<double>(std::stoi(line)) / 1000.0;
```

Potrzebujemy takiej precyzji ?

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/temp_driver.cpp
> +    std::ifstream file(kSensorPath + sensorPhysicalID + "/temperature");
```suggestion
    const std::ifstream file(kSensorPath + sensorPhysicalID + "/temperature");
```

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/sim_temp_driver.cpp
> +
trzeba pomyśleć nad możliwością wstrzykiwania tych

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/sim_temp_driver.cpp
> +     ara::log::LoggingMenager::GetInstance()->CreateLogger("TEMP", "", ara::log::LogLevel::kInfo);
```suggestion
     ara::log::LoggingMenager::GetInstance()->CreateLogger("Dtem", "", ara::log::LogLevel::kInfo);
```

2024-11-08 13:40 UTC, bartoszsnieg commented on core/temp/sim_temp_driver.cpp
> +     ara::log::LoggingMenager::GetInstance()->CreateLogger("TEMP", "", ara::log::LogLevel::kInfo);
Musimy je jakoś grupować tak jak ja mam np ara, acom, adia itp.

2024-11-08 13:40 UTC, bartoszsnieg commented on core/i2c/sim_i2c_driver.cpp
> +  ara::log::LogInfo() << "READ Data size:" << size;
```suggestion
  ara::log::LogDebug() << "READ Data size:" << size;
```

2024-11-08 13:40 UTC, bartoszsnieg commented on core/i2c/sim_i2c_driver.cpp
> +  ara::log::LogInfo() << "READ Data size:" << size;
i tak dla reszty bo bedziemy mieli spam

2024-11-08 13:40 UTC, bartoszsnieg commented on core/gpio/sim_gpio_driver.cpp
> +    direction_t direction = direction_t::IN;
```suggestion
    const direction_t direction = direction_t::IN;
```

2024-11-08 13:40 UTC, bartoszsnieg commented on core/gpio/sim_gpio_driver.cpp
> +    direction_t direction = direction_t::IN;
itp

2024-11-08 15:31 UTC, Mateusz-Krajewski commented on core/temp/temp_driver.cpp
> +        double value = std::stoi(line) / 1000.0;
moglby byc float bo to jest i tak 9bit

2024-11-08 15:32 UTC, Mateusz-Krajewski commented on core/i2c/sim_i2c_driver.cpp
> +  ara::log::LogInfo() << "READ Data size:" << size;
przy symulacji chcialem osiagnac spam

2024-11-12 15:18 UTC, merged