i2c dodane
Simba-Avionic/srp pull request #26
Opened 2024-01-14 14:27 UTC by Michal-Mankowski

2024-01-14 15:56 UTC, bartoszsnieg commented
Masz błędy w   składni i ccp_lint nie przeszedł

2024-01-22 15:45 UTC, bartoszsnieg requested changes
Nie jest źle ale trochę do poprawy

2024-02-07 17:58 UTC, bartoszsnieg commented
Dalej check nie przechodzi niestety

2024-02-07 17:59 UTC, bartoszsnieg commented
błąd w rebase więc troche lipa

2024-02-07 18:04 UTC, bartoszsnieg requested changes

2024-02-07 18:04 UTC, bartoszsnieg commented on core/i2c/i2cdriver.cpp
> +Result<uint8_t> I2C::i2c_smbus_read_byte_data(uint8_t command) {
```suggestion
    args.read_write = read_write;
    args.command = command;
    args.size = size;
    args.data = data;
    return ioctl(this->file, I2C_SMBUS, &args);
}
Result<uint8_t> I2C::i2c_smbus_read_byte_data(const uint8_t command) {
```

2024-02-07 18:04 UTC, bartoszsnieg commented on core/i2c/i2cdriver.h
> +#include <sys/ioctl.h>
```suggestion
#define CORE_I2C_I2CDRIVER_H_

#include <sys/ioctl.h>
```

2024-02-07 18:04 UTC, bartoszsnieg commented on core/i2c/BUILD
> +    deps = ["//core"],
wyjdzie błędne koło unikaj czegoś takiego

2024-02-07 18:04 UTC, bartoszsnieg commented on core/i2c/BUILD
> +    deps = ["//core"],
to był nasz błąd i w nowych libkach to naprawiamy

2024-02-07 18:04 UTC, bartoszsnieg commented on core/i2c/i2cdriver.cpp
> +    return kOk;
Wygląda lepiej 
```suggestion
    return ErrorCode::kOk;
```

2024-02-07 18:04 UTC, bartoszsnieg commented on core/i2c/i2cdriver.h
> +    ErrorCode read(const uint8_t address, const uint8_t reg, std::vector<uint8_t>& vect);
Troche slabo jest przez referencje bo cpplint bedzie wywalal sie + mozesz uzyc core::Result<td::vector<uint8_t>> jako zwracanie i jak bedzie blad to zwracamy pusty obiekt
```suggestion
    ErrorCode read(const uint8_t address, const uint8_t reg, std::week_ptr<std::vector<uint8_t>> vect);
```

2024-02-08 22:13 UTC, bartoszsnieg requested changes
Było jakoś testowane ?

2024-02-08 22:13 UTC, bartoszsnieg commented on core/common/crc_16.cc
> +}  // namespace simba
Co tutaj się stało ?

2024-03-11 19:12 UTC, Mateusz-Krajewski approved these changes
ok

2024-03-11 19:13 UTC, merged