Makr remove result fix core dep
Simba-Avionic/srp pull request #43
Opened 2024-03-07 11:27 UTC by Mateusz-Krajewski

2024-03-08 10:19 UTC, bartoszsnieg requested changes

2024-03-08 10:19 UTC, bartoszsnieg commented on apps/example/router.h
> -class Router : public core::ApplicationNoIPC{
on powinien uzyc application klasy tylko jej nie ma

2024-03-08 10:19 UTC, bartoszsnieg commented on communication-core/someip-controller/BUILD
> +    deps = [],
mozna usunac
```suggestion
```

2024-03-08 10:19 UTC, bartoszsnieg commented on core/application/application_common.cc
> +  auto service_id_ = obj.GetNumber<uint16_t>("app_id");
app_id jak dla mnie

2024-03-08 10:19 UTC, bartoszsnieg commented on core/application/application_common.h
> +  diag::exec::ExecController exec_;
nie lepiej zeby to byl wskaźnik ?

2024-03-08 10:19 UTC, bartoszsnieg commented on core/application/application_common.h
> +  diag::exec::ExecController exec_;
po co marnowac pamiec jak i tak nie uzywamy tego ?

2024-03-08 10:19 UTC, bartoszsnieg commented on core/json/json_parser.h
> +#include <optional>
cpplint to sprawdził ?

2024-03-08 10:21 UTC, Mateusz-Krajewski commented on core/json/json_parser.h
> +#include <optional>
No przeszedł action

2024-03-10 19:50 UTC, bartoszsnieg approved these changes
Działa to ?

2024-03-10 19:50 UTC, bartoszsnieg commented on communication-core/someip-controller/someip_controller.h
>  #include "memory"
brak #include optional

2024-03-10 19:50 UTC, bartoszsnieg commented on communication-core/someip-controller/transfer.h
>  namespace simba {
brak #include optional

2024-03-10 19:50 UTC, bartoszsnieg commented on core/application/application_mw.cc
> +  }
to mozna do osobnej funkcji w protected w common. Po co to samo implementowac 2 razy

2024-03-10 19:50 UTC, bartoszsnieg commented on core/json/json_parser.cc
> +    return std::optional<JsonParser>{};
można
```suggestion
    return {};
```

2024-03-10 19:50 UTC, bartoszsnieg commented on core/json/json_parser.cc
> +    return std::optional<JsonParser>{};
```suggestion
    return {};
```

2024-03-10 19:50 UTC, bartoszsnieg commented on core/json/json_parser.cc
> +  return std::optional<JsonParser>{JsonParser{f}};
```suggestion
  return JsonParser{f};
```

2024-03-10 19:50 UTC, bartoszsnieg commented on core/json/json_parser.cc
> +    return std::optional<std::string>{};
to samo co wyzej

2024-03-10 19:50 UTC, bartoszsnieg commented on core/json/json_parser.h
> +      return std::optional<T>{};
to samo co wyzej

2024-03-10 19:50 UTC, bartoszsnieg commented on core/logger/logger_factory.cc
> +    return std::optional<std::shared_ptr<ILogger>>{};
nie potrzeba 
 patrz wcześniej

2024-03-10 20:26 UTC, Mateusz-Krajewski commented
> Działa to ?

działa poza exec manager, dzięki za uwage

2024-03-10 21:50 UTC, merged