Add TemperatureController
Simba-Avionic/srp pull request #46
Opened 2024-03-11 12:35 UTC by mmatuszewsky

This PR adds TemperatureController which is responsible for getting readings from DS18B20 sensors as well as sending those readings to interested services.

Readings are represented as **std::pair<uint16_t, double>,** where _first_ is senor_id given in **temp_config.json** and _second_ is value from that sensor.

Subscription is made by sending SubscribeHeader message with service_id.

Tested:
- subscription via SubscribeHeader message
- sending / serializing / receiving data between services via IPC
- acquiring data from DS18B20 sensor

2024-03-11 17:22 UTC, bartoszsnieg requested changes
Są konflikty bo fix z pamięcią wszedł na mastera bez kolejki

2024-03-13 13:08 UTC, Mateusz-Krajewski requested changes
Troche do poprawy

2024-03-13 13:08 UTC, Mateusz-Krajewski commented on mw/temp/temp_reading_msg/temp_reading_msg_factory.cpp
to napewno działa?

2024-03-13 13:08 UTC, Mateusz-Krajewski commented on mw/temp/temp_reading_msg/temp_reading_msg.h
> + public:
ta klasaa nie powinna mieć chodziać sensor_id jako daną?

2024-03-13 13:08 UTC, Mateusz-Krajewski commented on mw/temp/controller/temp_controller.h
> +    virtual void Callback(const std::string& ip, const std::uint16_t& port,
tu chyba lepszy byłby model że moge ustawić swój callback jak w socket

2024-03-13 13:08 UTC, Mateusz-Krajewski commented on mw/temp/controller/temp_controller.h
> +    virtual void Callback(const std::string& ip, const std::uint16_t& port,
bo serwis który będzie z tego korzystał na 95% będzie przekazywał dalej te informacje

2024-03-13 13:10 UTC, mmatuszewsky commented on mw/tempService/temp_reading_msg/temp_reading_msg.cpp
czyli readingi wysyłać tylko jako payload, bez headera?

2024-03-13 13:17 UTC, mmatuszewsky commented on mw/temp/temp_reading_msg/temp_reading_msg_factory.cpp
są UT napisane na to

2024-03-13 14:59 UTC, Mateusz-Krajewski commented
temp-service-dep

2024-03-13 15:59 UTC, Mateusz-Krajewski approved these changes

2024-03-14 10:57 UTC, bartoszsnieg requested changes
Jak sprawdzimy na BBB to wtedy

2024-04-08 06:16 UTC, closed without merging