Makr moc create exec manager
Simba-Avionic/srp pull request #49
Opened 2024-03-14 10:15 UTC by Mateusz-Krajewski

2024-03-14 10:55 UTC, bartoszsnieg approved these changes

2024-03-14 10:55 UTC, bartoszsnieg commented on communication-core/json-parser/BUILD
ten plik bedzie trzeba kiedys usunąć

2024-03-14 10:55 UTC, bartoszsnieg commented on communication-core/someip-controller/mock/BUILD
> +        ],
```suggestion
        ],
        testonly = True,
```

2024-03-14 10:55 UTC, bartoszsnieg commented on core/application/mock/BUILD
> +    visibility = ["//visibility:public"],
```suggestion
        ],
        testonly = True,
    visibility = ["//visibility:public"],
```

2024-03-14 10:55 UTC, bartoszsnieg commented on core/gpio/mock/BUILD
> +    visibility = ["//visibility:public"],
```suggestion
        ],
        testonly = True,
    visibility = ["//visibility:public"],
```

2024-03-14 10:55 UTC, bartoszsnieg commented on core/gpio/mock/mock_gpio_driver.h
> +};
brak HEADER GUARD i EOF

2024-03-14 10:55 UTC, bartoszsnieg commented on core/i2c/BUILD
> +        "Ii2cdriver.hpp",
weź używaj h bo to potem dziwnie wygląda

2024-03-14 10:55 UTC, bartoszsnieg commented on core/gpio/mock/mock_gpio_driver.h
> +class MockGPIO : public simba::core::gpio::IgpioDigitalDriver {
możesz namespace po dodawac bo tutaj dziwnie wyglada to simba:: ....

2024-03-14 10:55 UTC, bartoszsnieg commented on core/i2c/Ii2cdriver.hpp
> +class II2C {
```suggestion
class Ii2cDriver {
```

2024-03-14 10:55 UTC, bartoszsnieg commented on core/i2c/i2cdriver.h
> +class I2C : public II2C {
```suggestion
class I2cDriver : public II2C {
```

2024-03-14 10:55 UTC, bartoszsnieg commented on core/i2c/mock/BUILD
> +    visibility = ["//visibility:public"],
```suggestion
        ],
        testonly=True,
    visibility = ["//visibility:public"],
```

2024-03-14 10:55 UTC, bartoszsnieg commented on core/i2c/mock/mock_i2cdriver.hpp
> +};
EOF i header guard

2024-03-14 10:55 UTC, bartoszsnieg commented on core/test/benchmark/sample_benchmark.cc
dziwna nazwa pliku jakby nie wynika z niej co testujesz

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/BUILD
> +)
Musiał byc dodany osobny ? + formatowanie

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/exec_controller.cpp
> +    this->mtx_status_.lock();
można to lepiej np  std::lock_guard<std::mutex> lock(mtx_status_);

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/exec_controller.cpp
> +    this->flags_ = std::bitset<5>{"00000"};
to tak musi być ?

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/exec_controller.cpp
>      auto factory_ = ExecMsgFactory();
const ???

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/exec_controller.cpp
> +    auto hdr = ExecHeader(service_id, 1, this->flags_.to_ulong() << 3 | this->status_);
nie podoba mi sie ta inicjalizacja sock_

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/exec_controller.cpp
>          sock_.Transmit("SIMBA.EXE", 0, data);
Nie ma dla mie to sensu troche czemu co 1 sekunde ?

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/exec_controller.cpp
> +    this->mtx_status_.unlock();
jak wcześniej można lepiej

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/controller/exec_controller.hpp
> +    void SetFlags(std::bitset<5> flags);
co robią te dwe funkcje ?

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/data/exec_header.cpp
> +}
a to jest też uzywane miedzy watkami

2024-03-14 10:55 UTC, bartoszsnieg commented on diag/exec/tests/exec_data_factory.cc
> +}
EOF

2024-03-14 10:55 UTC, bartoszsnieg commented on mw/em/code/BUILD
> +        #"//mw/em/code/services/exec:exec_service",
do usunięcia

2024-03-14 10:55 UTC, bartoszsnieg commented on mw/em/code/services/em/app_config.h
> +            const uint8_t startup_prio, const uint8_t startup_after_delay, uint16_t appID)
```suggestion
            const uint8_t startup_prio, const uint8_t startup_after_delay, const uint16_t appID)
```

2024-03-14 10:55 UTC, bartoszsnieg commented on mw/em/code/services/exec/BUILD
> +        "//mw:__subpackages__",
czemu aż tak ?

2024-03-14 10:55 UTC, bartoszsnieg commented on mw/gpio_server/controller/gpio_controller.hpp
> +    com::soc::ISocket* sock_;
czemu ten a nie smart ?

2024-03-14 10:55 UTC, bartoszsnieg commented on mw/gpio_server/tests/test_controller.cpp
> +};
EOF

2024-03-14 10:56 UTC, bartoszsnieg requested changes
Pomyłka

2024-03-14 11:02 UTC, Mateusz-Krajewski commented
> Pomyłka

sory zapomniaem zmienić na draft

2024-03-24 11:41 UTC, bartoszsnieg approved these changes

2024-03-24 12:29 UTC, merged