Create Devcontainer
Simba-Avionic/srp pull request #62
Opened 2024-04-10 19:42 UTC by Mateusz-Krajewski

2024-04-11 06:35 UTC, bartoszsnieg approved these changes
według mnie przerost formy nad treścią ale ok. Bardziej to coś takiego do symulacji ecu by było potrzebne że można resetować itp.

2024-04-11 06:36 UTC, bartoszsnieg requested changes
Czekaj ale na co to w sumie ??

2024-04-11 06:40 UTC, Mateusz-Krajewski commented
> Czekaj ale na co to w sumie ??

Jakby ktoś sobie nie radził, to masz gotowe środowisko z wszystkimi ustawieniami. Wystarczy mieć vscode i docker i pobrać nasze repo, reszta się doinstaluje

2024-04-11 11:48 UTC, Mateusz-Krajewski commented
chce zrobić pełne środowisko z zainstalowanym wireshark,qemu, dlt viewer, które będzie w prosty sposób umożliwiało testowanie kodu

2024-04-12 14:00 UTC, bartoszsnieg submitted a review, later dismissed
ok

2024-04-12 14:25 UTC, merged